server:
  port: 9761

spring:
  application:
    name: skillsync-eureka-server

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN